
services:
 
  # fastapi_app:
  #   build: ./fastapi_app
  #   volumes:
  #     - ./models:/app/models
  #   container_name: fastapi_app
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   env_file:
  #     - .env
  #   ports:
  #     - "8001:8000"
  #   networks:
  #     - my_network

  
  # redis:
  #   image: redis:latest
  #   container_name: redis_cache
  #   restart: always
  #   ports:
  #     - "6379:6379"

  #   networks:
  #     - my_network
  admin_service:
    build:
      context: ./admin_service
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8003:8000"
    networks:
      - my_network
  org_service:
    build:
      context: ./org_service
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8004:8000"
    networks:
      - my_network

  team_service:
    build:
      context: ./team_service
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8002:8000"
    networks:
      - my_network



  users_service:
    build:
      context: ./users_service
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8001:8000"
    networks:
      - my_network

  db:
    image: postgres:15
    container_name: bcs_db
    restart: always
    environment:
      POSTGRES_USER: bcs
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bcs
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  pgdata:
 

networks:
  my_network: